// Focus pick data, transcribed from "Ars Belli MP Mod - Design Doc - Focus Picks.md".
// Each branch: 6 advances. Entry: [key, modifiers(string lines), extra]
// extra: { name, desc } for new keys (abm_*), { icon } override, { raw } extra raw lines.
// Value rule: reused vanilla advance keeps vanilla value unless the doc marks "(was X)" or adds a new stat.
module.exports = {
 ages: [
 { age: 'age_2_renaissance', n: 2,
   eco: [
    { id: 'court', name: 'Court', desc: 'Administrative and court efficiency.', adv: [
      ['innovativeness', 'global_max_literacy = 5'],
      ['state_efficiency', 'global_distance_from_capital_speed_propagation = 0.1'],
      ['court_accounting', 'court_spending_efficiency = 0.1'],
      ['dynamic_court', 'country_cabinet_efficiency = 0.10'],
      ['church_attendance_duty', 'stability_investment = small_stability_investment'],
      ['empiricism', 'legislative_efficiency = 0.20\nset_policy_cost_modifier = -0.66\nchange_policy_cost_modifier = -0.20'],
    ]},
    { id: 'trade', name: 'Trade', desc: 'Markets, merchants and trade range.', adv: [
      ['shrewd_commerce_practice', 'global_trade_center_power = 0.10'],
      ['merchant_traditions', 'merchant_power_from_maritime_modifier = 0.1'],
      ['additional_merchants', 'global_merchant_capacity_modifier = 0.25'],
      ['merchant_adventures', 'trade_sea_efficiency = medium_trade_sea_efficiency_bonus'],
      ['debt_and_loans', 'bank_interest = -0.01\nmax_bonds = 1'],
      ['abm_protected_trade_caravans', 'trade_land_efficiency = medium_trade_land_efficiency_bonus', { icon: 'expanded_supply_trains', name: 'Protected Trade Caravans', desc: 'Armed escorts and fortified caravanserais along our overland routes let our merchants reach far-off markets without the expense of a fleet.' }],
    ]},
    { id: 'influence', name: 'Influence', desc: 'Subjects, vassals and diplomats.', adv: [
      ['integrated_elites', 'monthly_diplomats = 0.2\nmax_diplomats = 1'],
      ['tribute_system', 'subject_income_modifier = 0.025\nsubject_loyalty = 5\nsubject_opinions = 25'],
      ['marcher_lords', '', { raw: 'unlock_subject_type = march' }],
      ['buffer_states', 'diplomatic_capacity = 1\ndiplomatic_reputation = diplomatic_reputation_mild_bonus'],
      ['benign_diplomats', 'improve_relation_impact = 0.25\nsubject_opinions = 10'],
      ['additional_loyalist_recruitment', 'subject_loyalty = 5'],
    ]},
   ],
   mil: [
    { id: 'levy', name: 'Levy', desc: 'Larger and better levies.', adv: [
      ['enforced_service', 'global_levy_size_modifier = 0.1'],
      ['open_levy_standards', 'wrong_culture_levy_size = 0.25'],
      ['regular_levy_training', 'levy_combat_efficiency_modifier = 0.10'],
      ['battlefield_commisions', 'army_tradition_from_battle = 1.0'],
      ['abm_local_militias', 'global_levy_recruitment_speed_modifier = 0.33\nlevy_maintenance_modifier = -0.5', { icon: 'regimental_system', name: 'Local Militias', desc: 'Townsmen and villagers drilled on the green each Sunday can be called to arms quickly and cost little to keep.' }],
      ['abm_feudal_obligations', 'levy_recovery_modifier = 0.10', { icon: 'defensive_army', name: 'Feudal Obligations', desc: 'Every lord owes his liege a set number of men each year, and the lists are kept up to date.' }],
    ]},
    { id: 'mercenary', name: 'Mercenary', desc: 'Cheaper and more available mercenaries.', adv: [
      ['benefits_for_mercenaries', 'mercenary_maintenance_efficiency = 0.1'],
      ['organised_mercenary_recruitment', 'mercenary_range_modifier = 0.5'],
      ['organised_mercenary_payment', 'hire_mercenary_premium_cost_modifier = -0.2'],
      ['glorious_arms', 'prestige_from_land_battle = 1.0'],
      ['abm_ensure_mercenary_payments', 'hire_mercenary_leader_cost_modifier = -0.75', { icon: 'regimental_system', name: 'Ensure Mercenary Payments', desc: 'A reputation for paying on time means the best condottieri will sign with us for far less.' }],
      ['tolerance_idea', 'tolerance_heretic = 0.5\ntolerance_heathen = 0.5'],
    ]},
    { id: 'maritime', name: 'Maritime', desc: 'Galleys, marines and early privateering.', adv: [
      ['improved_rams', 'navy_galley_power = 0.15\nnavy_galley_maintenance_cost_modifier = -0.10'],
      ['boarding_parties', 'naval_damage_done = 0.1'],
      ['marine_regiments', 'army_disembark_speed = 0.33'],
      ['naval_glory', 'navy_tradition_from_battle = 1.0\nprestige_from_naval_battle = 1.0'],
      ['privateers', 'can_hire_privateers = yes\nanti_piracy_warfare_modifier = 0.25'],
      ['ships_penny', 'ship_build_speed = 0.25'],
    ]},
   ]},
 { age: 'age_3_discovery', n: 3,
   eco: [
    { id: 'infrastructure', name: 'Infrastructure', desc: 'Construction, roads and mining.', adv: [
      ['organised_construction', 'global_build_buildings_efficiency = 0.2'],
      ['efficient_construction_plans', 'global_urban_build_buildings_efficiency = 0.2'],
      ['expanded_infrastructure_network', 'global_road_building_time = -0.1\nbuild_gravel_road_cost_modifier = -0.1\nbuild_paved_road_cost_modifier = -0.1\nbuild_modern_road_cost_modifier = -0.1'],
      ['efficient_mining', 'expand_rgo_mining_cost_modifier = -0.1\nglobal_iron_output_modifier = 0.1\nglobal_copper_output_modifier = 0.1'],
      ['rgo_logistics_mil_choice', 'raw_material_in_province_impact = 0.025'],
      ['advanced_bureaucracy', 'tax_income_efficiency = small_tax_income_efficiency_bonus\nglobal_bureaucracy_maintenance_efficiency = 0.04'],
    ]},
    { id: 'exploration', name: 'Exploration', desc: 'Exploration, colonisation and overseas trade.', adv: [
      ['quest_for_the_new_world', 'exploration_preparation_time_modifier = -0.25\nexploration_mission_speed = 0.1', { raw: 'ai_preference_tags = {\n\texploration\n}' }],
      ['exploration', 'colonial_range = 500', { raw: 'unlock_casus_belli = cb_exploration\n\nai_preference_tags = {\n\texploration\n}' }],
      ['overseas_exploration', 'colonial_range_modifier = 0.5', { raw: 'ai_preference_tags = {\n\texploration\n}' }],
      ['faster_colonists', 'colonial_migration_size_modifier = 0.25', { raw: 'ai_preference_tags = {\n\texploration\n}' }],
      ['colonial_ventures', 'colonial_migration_size_modifier = 0.25', { raw: 'ai_preference_tags = {\n\texploration\n}' }],
      ['overseas_trade', 'trade_range_modifier = 0.5'],
    ]},
    { id: 'diplomatic', name: 'Diplomatic', desc: 'The diplomacy of conquest.', adv: [
      ['flexible_negotiation', 'global_war_score_efficiency = 0.2'],
      ['formal_diplomacy', 'diplomatic_reputation = diplomatic_reputation_mild_bonus\nimprove_relation_impact = 0.30'],
      ['diplomatic_influence', 'diplomatic_reputation = diplomatic_reputation_mild_bonus\ndiplomatic_capacity = 1'],
      ['adaptability', 'antagonism_received_modifier = -0.3'],
      ['diplomatic_corps', 'monthly_diplomats = 0.1\ncasus_belli_creation_speed_modifier = 0.25'],
      ['indirect_rule', 'global_separatism = -0.1\nglobal_integration_speed_modifier = 0.1'],
    ]},
   ],
   mil: [
    { id: 'quality', name: 'Quality', desc: 'Better-led, better-drilled armies.', adv: [
      ['formalized_officer_corps', 'army_initiative = 0.25'],
      ['administrative_leadership', 'hire_advisor_cost_modifier = -0.25\ntrain_general_cost_modifier = -0.25\ntrain_admiral_cost_modifier = -0.25'],
      ['quality_education', 'monthly_army_tradition = 0.1'],
      ['abm_drill_sergeants', 'monthly_experience_gain = 0.5', { icon: 'offensive_army', name: 'Drill Sergeants', desc: 'Veteran sergeants put every company through its paces daily, turning raw recruits into seasoned soldiers in half the time.' }],
      ['abm_trained_march', 'land_morale_movement_cost = -0.0002', { icon: 'expanded_supply_trains', name: 'Trained March', desc: 'Regulated marching pace and rest halts keep our columns in good order and good spirits on the road.' }],
      ['military_drill', 'land_morale_modifier = 0.10', { raw: 'ai_weight = { add = 10 }' }],
    ]},
    { id: 'quantity', name: 'Quantity', desc: 'Manpower, reinforcement and logistics.', adv: [
      ['abm_rapid_reinforcement', 'combat_speed_modifier = 0.10', { icon: 'regimental_system', name: 'Rapid Reinforcement', desc: 'Reserve companies are moved up to the line as soon as the front ranks falter, keeping the pressure on the enemy.' }],
      ['camp_followers', 'global_supply_limit_modifier = 0.1'],
      ['the_old_and_infirm', 'army_maintenance_efficiency = 0.1'],
      ['abm_deep_reserves', 'army_reinforce_efficiency = 0.2', { icon: 'defensive_army', name: 'Deep Reserves', desc: 'Depots of trained replacements stand ready behind every army, so losses are made good cheaply.' }],
      ['supply_trains', 'food_consumption_modifier = -0.10'],
      ['grand_army', 'global_manpower_modifier = 0.10'],
    ]},
    { id: 'naval', name: 'Naval', desc: 'Heavy and light ships.', adv: [
      ['oak_forests_for_ships', 'navy_heavy_ship_power = 0.10\nnavy_heavy_ship_maintenance_cost_modifier = -0.10'],
      ['abm_patrol_vessels', 'navy_light_ship_power = 0.10\nnavy_light_ship_build_cost_modifier = -0.20\nnavy_light_ship_maintenance_cost_modifier = -0.10', { icon: 'naval_morale_advance_1', name: 'Patrol Vessels', desc: 'Swift, cheap cruisers guard our coasts and shipping lanes, freeing the great ships for battle.' }],
      ['abm_naval_education', 'monthly_navy_tradition = 0.1', { icon: 'naval_morale_advance_1', name: 'Naval Education', desc: 'Schools of navigation and gunnery produce a steady stream of capable officers for the fleet.' }],
      ['copper_bottoms', 'naval_unit_attrition = -0.25'],
      ['naval_drill', 'naval_morale_modifier = 0.10'],
      ['grand_navy', 'navy_maintenance_efficiency = 0.1'],
    ]},
   ]},
 { age: 'age_4_reformation', n: 4,
   eco: [
    { id: 'religion', name: 'Religion', desc: 'Conversion and assimilation to the true faith.', adv: [
      ['devoutness', 'tolerance_own = 1'],
      ['religious_tradition', 'monthly_prestige = 0.1\ncultural_tradition_modifier = 0.2'],
      ['abm_cultural_unity', 'global_pop_assimilation_speed_modifier = 0.2', { icon: 'cultural_ties', name: 'Cultural Unity', desc: 'One realm, one people: schools, sermons and law courts all speak the language of the crown.' }],
      ['preaching_missions', 'global_pop_assimilation_speed_modifier = 0.1\nglobal_pop_conversion_speed_modifier = 0.1'],
      ['divine_supremacy', 'global_pop_conversion_speed_modifier = 0.20'],
      ['missionary_schools', 'global_pop_conversion_speed = 0.01'],
    ]},
    { id: 'expansion', name: 'Expansion', desc: 'Late colonisation and overseas trade.', adv: [
      ['free_colonies', 'colonial_maintenance_efficiency = 0.40'],
      ['land_of_opportunity', 'colonial_migration_size_modifier = 0.25'],
      ['additional_colonists', 'colonial_migration_size_modifier = 0.25'],
      ['vice_roys', 'subject_pays_colonial_cost_modifier = 0.50\ndiplomatic_range_modifier = 0.25'],
      ['merchant_power_from_maritime_rev_dip_choice', 'merchant_power_from_maritime_modifier = 0.1'],
      ['overseas_merchants', 'trade_range_modifier = 0.5'],
    ]},
    { id: 'humanism', name: 'Humanism', desc: 'Religious and cultural tolerance.', adv: [
      ['ecumenism', 'tolerance_heretic = 1.5'],
      ['humanist_tolerance', 'tolerance_heathen = 1.5'],
      ['abm_integration_of_cultures', 'add_accepted_culture_cost_modifier = -0.5\nchange_primary_culture_cost_modifier = -0.5', { icon: 'cultural_ties', name: 'Integration of Cultures', desc: 'Welcoming new peoples into the heart of the realm is no longer a matter of controversy.' }],
      ['cultural_ties', 'cultures_capacity = 2'],
      ['abm_compromise', 'monthly_rebel_growth = -0.001\nmonthly_religious_rebel_growth = -0.001\npop_leave_rebels_threshold = -0.05', { icon: 'cultural_acceptance_advance', name: 'Compromise', desc: 'Listening to grievances before they turn into rebellions keeps the peace at home.' }],
      ['cultures_capacity_mil_choice', 'cultures_capacity_modifier = 0.25'],
    ]},
   ],
   mil: [
    { id: 'offense', name: 'Offense', desc: 'Sieges and artillery.', adv: [
      ['expanded_supply_trains', 'land_unit_attrition = -0.15'],
      ['abm_night_assaults', 'assault_ability = 0.20', { icon: 'offensive_army', name: 'Night Assaults', desc: 'Storming parties go over the walls under cover of darkness, when the defenders least expect it.' }],
      ['engineer_corps', 'siege_ability = 0.20'],
      ['abm_standardized_barrels', 'army_artillery_build_cost_modifier = -0.10\nglobal_cannons_output_modifier = 0.05', { icon: 'efficient_mining', name: 'Standardized Barrels', desc: 'Fixed calibres and bore sizes let our foundries cast guns quickly and interchangeably.' }],
      ['superior_firepower', 'army_artillery_power = 0.1'],
      ['abm_siege_artillery', 'artillery_bonus_vs_fort = 1', { icon: 'offensive_army', name: 'Siege Artillery', desc: 'Heavy guns built for one purpose: bringing down walls.' }],
    ]},
    { id: 'defense', name: 'Defense', desc: 'Forts and garrisons.', adv: [
      ['defensive_army', 'global_hostile_attrition = 1'],
      ['garrison_conscription', 'global_garrison_size_modifier = 0.20\nglobal_garrison_growth = 0.025'],
      ['defensive_mentality', 'global_defensive = 0.2'],
      ['abm_earthworks', 'global_fort_build_buildings_efficiency = 0.4', { icon: 'defensive_mentality', name: 'Earthworks', desc: 'Packed earth and timber ramparts can be thrown up quickly and cheaply, and they shrug off cannon fire better than stone.' }],
      ['fort_logistics', 'fort_maintenance_efficiency = 0.2'],
      ['abm_fortified_cities_focus', 'fort_limit_modifier = 0.10\nfort_limit = 8', { icon: 'defensive_mentality', name: 'Fortified Cities', desc: 'Every town of note is ringed by modern bastions.' }],
    ]},
    { id: 'littoral_fleet', name: 'Littoral Fleet', desc: 'Galleys and building up a navy quickly.', adv: [
      ['abm_gun_galleys', 'navy_galley_power = 0.10\nnavy_galley_build_cost_modifier = -0.20', { icon: 'naval_morale_advance_1', name: 'Gun Galleys', desc: 'Galleys mounting heavy bow guns remain masters of calm coastal waters.' }],
      ['naval_cadets', 'navy_initiative = 0.75'],
      ['merchant_marine', 'global_sailors_modifier = 0.20'],
      ['improved_shipyards', 'ship_build_speed = 0.50'],
      ['abm_home_fleet', 'own_coast_naval_combat_bonus = 0.15', { icon: 'naval_morale_advance_1', name: 'Home Fleet', desc: 'Squadrons trained to fight in the shoals and narrows they know best.' }],
      ['sheltered_ports', 'navy_repair_efficiency = 0.3'],
    ]},
   ]},
 { age: 'age_5_absolutism', n: 5,
   eco: [
    { id: 'administration', name: 'Administration', desc: 'Control, cabinet and legislation.', adv: [
      ['cabinet', 'country_cabinet_efficiency = 0.20'],
      ['national_bank', 'minting_income_factor = 0.10\nmax_bonds = 1'],
      ['civil_servants', 'global_monthly_control = 0.001\nglobal_monthly_control_decline = -0.002'],
      ['legislative_efficiency_idea', 'legislative_efficiency = 0.25\nchange_policy_cost_modifier = -0.25'],
      ['centralized_government', 'global_distance_from_capital_speed_propagation = 0.1'],
      ['economic_ideas', 'global_monthly_development = 0.001'],
    ]},
    { id: 'commerce', name: 'Commerce', desc: 'Trade advantage, capacity and banking.', adv: [
      ['competetive_merchants', 'global_merchant_power = 0.2'],
      ['national_trade_policy', 'selling_efficiency = small_trade_efficiency_bonus'],
      ['fast_negotiations', 'merchant_maintenance_efficiency = 0.20'],
      ['free_trade', 'global_merchant_capacity_modifier = 0.20'],
      ['trade_manipulation', 'global_trade_center_power = 0.10'],
      ['bookkeeping', 'bank_interest = -0.01\nmax_bonds = 1'],
    ]},
    { id: 'espionage', name: 'Espionage', desc: 'Spies, infiltration and stolen research.', adv: [
      ['vetting', 'counter_espionage = 0.33'],
      ['efficient_spies', 'spy_network_construction = 0.5'],
      ['infiltrate_administration_advance', '', { raw: 'unlock_diplomacy = { infiltrate_administration }' }],
      ['foreign_embassies', 'monthly_diplomats = 0.1\nmax_diplomats = 1'],
      ['abm_global_networks', 'diplomatic_range_modifier = 0.5\ndiplomatic_range = 500', { icon: 'diplomatic_influence', name: 'Global Networks', desc: 'Our envoys, agents and correspondents reach every court of note, however distant.' }],
      ['abm_industrial_espionage', '', { icon: 'efficient_spies', name: 'Industrial Espionage', desc: 'Why pay for discoveries when our agents can simply copy them?', raw: 'unlock_country_interaction = steal_technology' }],
    ]},
   ],
   mil: [
    { id: 'maneuver', name: 'Maneuver', desc: 'Movement and combat speed.', adv: [
      ['improved_manuever', 'combat_speed_modifier = 0.10'],
      ['abm_forced_march', 'army_movement_speed = 0.10', { icon: 'expanded_supply_trains', name: 'Forced March', desc: 'Our armies are trained to cover great distances at speed when the campaign demands it.' }],
      ['land_morale_movement_cost_rev_choice_mil', 'land_morale_movement_cost = -0.0002'],
      ['abm_bold_maneuvers', 'movement_speed_if_no_road = 0.20', { icon: 'offensive_army', name: 'Bold Maneuvers', desc: 'Our generals do not wait for roads; they march across country and appear where the enemy least expects them.' }],
      ['abm_limbers', 'army_movement_speed = 0.05', { icon: 'offensive_army', name: 'Limbers', desc: 'Two-wheeled carriages let our guns be hitched to horses and keep pace with the rest of the army.' }],
      ['offensive_army', 'land_morale_recovery = 0.02'],
    ]},
    { id: 'logistics', name: 'Logistics', desc: 'Attrition, supply and auxiliaries.', adv: [
      ['abm_enduring_hardships', 'land_morale_attrition_cost = -0.25', { icon: 'improved_foraging', name: 'Enduring Hardships', desc: 'Hunger and disease no longer break the spirit of our soldiers as easily as they once did.' }],
      ['improved_foraging', 'land_unit_attrition = -0.20'],
      ['abm_prepared_camps', 'global_supply_limit_modifier = 0.10', { icon: 'expanded_supply_trains', name: 'Prepared Camps', desc: 'Camp sites along our lines of march are surveyed and stocked in advance.' }],
      ['improved_logistics', 'army_logistics_distance_modifier = 0.10'],
      ['abm_logistics_corps', 'army_auxiliary_power = 0.50\narmy_auxiliary_build_cost_modifier = -0.20\narmy_auxiliary_maintenance_cost_modifier = -0.10', { icon: 'expanded_supply_trains', name: 'Logistics Corps', desc: 'Wagoners, sappers and sutlers are organised into proper units that can defend themselves when caught out.' }],
      ['abm_trained_reserves', 'regiment_reinforcement_speed = 0.10', { icon: 'defensive_army', name: 'Trained Reserves', desc: 'Replacements arrive at the front already trained and equipped.' }],
    ]},
    { id: 'highseas_fleet', name: 'Highseas Fleet', desc: 'Heavy ships and blue-water warfare.', adv: [
      ['abm_ships_of_the_line', 'navy_heavy_ship_power = 0.10\nnavy_heavy_ship_build_cost_modifier = -0.20', { icon: 'naval_morale_advance_1', name: 'Ships of the Line', desc: 'Great three-deckers built to a standard pattern form the backbone of our battle fleet.' }],
      ['sea_hawks', 'navy_initiative = 0.75'],
      ['escort_ships', 'naval_damage_taken = -0.1'],
      ['superior_seamanship', 'naval_morale_modifier = 0.1'],
      ['naval_fighting_instruction', 'blockade_efficiency = 0.5\nship_repair_at_sea = 0.025'],
      ['press_gangs', 'navy_repair_efficiency = 0.3'],
    ]},
   ]},
 { age: 'age_6_revolutions', n: 6,
   eco: [
    { id: 'industry', name: 'Industry', desc: 'Production, extraction and taxes. The tall pick.', adv: [
      ['audit_checks', 'tax_income_efficiency = large_tax_income_efficiency_bonus'],
      ['formal_administration', 'government_size = 1'],
      ['smithian_economics', 'global_production_efficiency = medium_production_efficiency_bonus\nglobal_monthly_development = 0.002'],
      ['regulation_bureau', 'minting_inflation_threshold = 0.02'],
      ['abm_industrial_scale_extraction', 'global_max_rgo_size_modifier = 0.20', { icon: 'efficient_mining', name: 'Industrial Scale Extraction', desc: 'Steam pumps and organised labour open mines and plantations on a scale never seen before.' }],
      ['abm_modern_extraction_methods', 'global_raw_material_output = 0.20', { icon: 'efficient_mining', name: 'Modern Extraction Methods', desc: 'Scientific agriculture and new machinery wring more from every field and seam.' }],
    ]},
    { id: 'empire', name: 'Empire', desc: 'Proximity, governors and subjects. The wide pick.', adv: [
      ['global_empire', 'subject_income_modifier = 0.05\ntax_income_efficiency = medium_tax_income_efficiency_bonus'],
      ['local_traditions', 'global_estate_target_satisfaction = small_permanent_target_satisfaction'],
      ['postal_service', 'road_cost_on_distance_from_capital = -2\nsea_cost_on_distance_from_capital_when_maritime = -1'],
      ['port_cost_distance_from_capital_choice_mil', 'port_cost_distance_from_capital = -5'],
      ['abm_imperial_administration', 'num_local_governors = 1', { icon: 'court_accounting', name: 'Imperial Administration', desc: 'A professional corps of governors administers the provinces in the name of the crown.' }],
      ['abm_overseas_holdings', 'num_naval_governors = 1', { icon: 'expansionism', name: 'Overseas Holdings', desc: 'Our possessions across the sea are placed under governors answerable directly to the capital.' }],
    ]},
    { id: 'innovation', name: 'Innovation', desc: 'Research, literacy and the arts. The science pick.', adv: [
      ['abm_national_academy_of_sciences', 'research_speed = 0.05', { icon: 'scholasticism', name: 'National Academy of Sciences', desc: 'A royal academy gathers the finest minds of the nation under one roof.' }],
      ['abm_the_scientific_method', 'research_speed_modifier = 0.25', { icon: 'scholasticism', name: 'The Scientific Method', desc: 'Observation, hypothesis and experiment replace received wisdom.' }],
      ['abm_belle_epoque', 'cultural_influence_modifier = 0.5\nwork_of_art_quality_modifier = 0.5\nartist_impact = 0.5\nglobal_monthly_art_start_chance = 0.5\nskill_of_new_artists = 0.5', { icon: 'scholasticism', name: 'Belle Époque', desc: 'Salons, galleries and opera houses make our capital the envy of the civilised world.' }],
      ['humanism', 'global_max_literacy = 10'],
      ['abm_universal_literacy', 'global_monthly_literacy = 0.1', { icon: 'scholasticism', name: 'Universal Literacy', desc: 'A school in every parish, and every child taught to read.' }],
      ['optimism', 'monthly_war_exhaustion = -0.05'],
    ]},
   ],
   mil: [
    { id: 'voluntary_service', name: 'Voluntary Service', desc: 'Fewer but better troops.', adv: [
      ['discipline_drills', 'discipline = 0.05'],
      ['abm_thorough_training', 'regiment_recruit_speed = -0.50\nmonthly_experience_gain = 0.25', { icon: 'offensive_army', name: 'Thorough Training', desc: 'No recruit takes the field before he has mastered his drill; it takes longer, but it shows.' }],
      ['regimental_system', 'army_maintenance_efficiency = 0.1\narmy_initiative = 0.25'],
      ['abm_skirmish_line', 'military_tactics = 0.10', { icon: 'offensive_army', name: 'Skirmish Line', desc: 'Light troops screen the main body, picking off officers and disrupting the enemy advance.' }],
      ['finest_of_horses', 'army_heavy_cavalry_power = 0.1\narmy_light_cavalry_power = 0.1\narmy_heavy_cavalry_maintenance_cost_modifier = -0.05\narmy_light_cavalry_maintenance_cost_modifier = -0.05'],
      ['bayonet_leaders', 'army_heavy_infantry_power = 0.1\narmy_light_infantry_power = 0.1'],
    ]},
    { id: 'conscription', name: 'Conscription', desc: 'Mass armies from a large population.', adv: [
      ['mass_army', 'global_manpower_modifier = 0.20\nglobal_levy_size_modifier = 0.10'],
      ['national_conscripts', 'regiment_recruit_speed = 0.5\nlevy_maintenance_modifier = -0.5'],
      ['nationalistic_enthusiasm', 'army_maintenance_efficiency = 0.1\nlevy_combat_efficiency_modifier = 0.10'],
      ['the_young_can_serve', 'army_reinforce_efficiency = 0.10\nlevy_recovery_modifier = 0.10'],
      ['massed_battery', 'army_artillery_power = 0.1\narmy_artillery_build_cost_modifier = -0.10'],
      ['private_to_marshal', 'army_heavy_infantry_build_cost_modifier = -0.20\narmy_light_infantry_build_cost_modifier = -0.20\narmy_heavy_infantry_reinforce_cost_modifier = -0.15\narmy_light_infantry_reinforce_cost_modifier = -0.15\narmy_heavy_infantry_maintenance_cost_modifier = -0.10\narmy_light_infantry_maintenance_cost_modifier = -0.10'],
    ]},
    { id: 'insurrection', name: 'Insurrection', desc: 'Defensive war for small countries fighting for survival.', adv: [
      ['abm_guerillas', 'max_manpower = 1\noccupation_time = 1.0', { icon: 'defensive_army', name: 'Guerillas', desc: 'Every hill and forest hides a band of partisans, and no occupier sleeps soundly in our land.' }],
      ['morale_recovery_rev_dip_choice', 'morale_recovery_in_friendly = 0.05'],
      ['abm_peoples_war', 'global_hostile_attrition = 1\nglobal_devastation_recovery = 0.01', { icon: 'defensive_army', name: "People's War", desc: 'The whole nation takes up arms; invaders find the land stripped bare and every village hostile.' }],
      ['abm_last_stand', 'global_garrison_size_modifier = 0.15\nglobal_defensive = 0.15', { icon: 'defensive_mentality', name: 'Last Stand', desc: 'Our garrisons will hold to the last man.' }],
      ['abm_national_resistance', 'monthly_war_exhaustion = -0.05\ncultural_tradition_modifier = 10', { icon: 'cultural_ties', name: 'National Resistance', desc: 'Defeat only hardens the resolve of our people and deepens their sense of who they are.' }],
      ['abm_foreign_fighters', 'mercenary_maintenance_efficiency = 0.5\nmercenary_range_modifier = 1.0', { icon: 'regimental_system', name: 'Foreign Fighters', desc: 'Volunteers from across the world flock to our cause.' }],
    ]},
   ]},
 ]
};
