// Generates the Ars Belli focus-pick system from focus_data.js:
//   in_game/common/advances/abm_focus_picks_economic.txt
//   in_game/common/advances/abm_focus_picks_military.txt
//   in_game/events/ages.txt                               (same-name replacement of vanilla)
//   main_menu/localization/english/abm_focus_picks_l_english.yml
//
// Usage (from repo root):  node .tools/scripts/focus_picks/generate_focus_picks.js
// Set EU5_GAME to override the vanilla game path used for icon lookup / REPLACE detection.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../..');
const GAME = process.env.EU5_GAME || 'E:/Steam/steamapps/common/Europa Universalis V/game';
const ADV_DIR = GAME + '/in_game/common/advances';
const { ages } = require('./focus_data.js');

const BOM = '\uFEFF';
const EOL = '\r\n';
const write = (rel, text, bom = true) => {
	fs.writeFileSync(path.join(ROOT, rel), (bom ? BOM : '') + text.replace(/\r?\n/g, EOL), 'utf8');
	console.log('wrote', rel);
};

// Vanilla advance blocks: key -> { file, icon }
const vanilla = {};
for (const f of fs.readdirSync(ADV_DIR).filter(f => f.endsWith('.txt'))) {
	const t = fs.readFileSync(path.join(ADV_DIR, f), 'utf8').replace(/^\uFEFF/, '');
	for (const m of t.matchAll(/^([A-Za-z_0-9]+)\s*=\s*\{([\s\S]*?)^\}/gm)) {
		const icon = (m[2].match(/^\s*icon\s*=\s*(\S+)/m) || [])[1];
		vanilla[m[1]] = { file: f, icon };
	}
}
const CHOICE_FILES = ['4_choices_adm.txt', '4_choices_dip.txt', '4_choices_mil.txt'];

const focusVar = id => `abm_focus_${id}`;
const MAX_CHANGES = 3; // focus changes each country may make after picking
const indent = (s, n) => s.split('\n').map(l => (l ? '\t'.repeat(n) + l : l)).join('\n');

// Tree shape per branch: 0 is the root, 1->2 hang off 0, 3->4->5 hang off 0.
const PARENT = [null, 0, 1, 0, 3, 4];

function advanceBlock(ageKey, branch, idx) {
	const [key, mods, extra = {}] = branch.adv[idx];
	const v = vanilla[key];
	if (!v && !key.startsWith('abm_')) throw new Error(`vanilla advance not found: ${key}`);
	if (v && key.startsWith('abm_')) throw new Error(`abm_ key collides with vanilla: ${key}`);
	// Keys that live outside the emptied 4_choices files must be REPLACE:d, not redefined.
	const replace = v && !CHOICE_FILES.includes(v.file);
	const icon = extra.icon || (v && v.icon); // no icon line -> engine default, as in vanilla
	const lines = [];
	lines.push(`${replace ? 'REPLACE:' : ''}${key} = {`);
	lines.push(`\tage = ${ageKey}`);
	if (icon) lines.push(`\ticon = ${icon}`);
	// Branch roots must be explicit roots (depth = 0, like vanilla age roots): an advance with neither
	// requires nor depth gets auto-attached under another node by the engine (Mercenary landed under Court).
	if (PARENT[idx] === null) lines.push('\tdepth = 0');
	else lines.push(`\trequires = ${branch.adv[PARENT[idx]][0]}`);
	lines.push('');
	// potential (not allow): branches not picked stay hidden, like vanilla `for = X` focus advances.
	// potential IS re-checked in game, so a branch appears once its pick sets the variable. Hidden
	// branches also stop unparented vanilla/country advances being auto-attached under them.
	lines.push(`\tpotential = { has_variable = ${focusVar(branch.id)} }`);
	if (mods) { lines.push(''); lines.push(indent(mods, 1)); }
	if (extra.raw) { lines.push(''); lines.push(indent(extra.raw, 1)); }
	lines.push('}');
	return lines.join('\n');
}

function advancesFile(kind) {
	const title = kind === 'eco' ? 'Economic' : 'Military';
	const out = [];
	out.push(`# Ars Belli focus picks - ${title} advances. GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js`);
	out.push('# Edit focus_data.js and re-run the generator instead of editing this file by hand.');
	out.push('#');
	out.push('# Each age offers 3 branches; the pick made in the age event (ages_of_eu.1 / abm_focus_picks.1)');
	out.push('# sets a country variable abm_focus_<branch>, which is the only gate on these advances.');
	out.push('# The engine adm/dip/mil age preference (`for = X`) is no longer used: vanilla 4_choices_*.txt are emptied.');
	for (const a of ages) {
		for (const br of a[kind]) {
			out.push('');
			out.push('############################');
			out.push(`# ${a.age} - ${br.name} (${focusVar(br.id)})`);
			out.push('############################');
			br.adv.forEach((_, i) => { out.push(''); out.push(advanceBlock(a.age, br, i)); });
		}
	}
	return out.join('\n') + '\n';
}

// Ages from index: the branch of age N can be picked once current_age is N or later.
const AGE_KEYS = ['age_2_renaissance', 'age_3_discovery', 'age_4_reformation', 'age_5_absolutism', 'age_6_revolutions'];
const ageReached = age => 'OR = { ' + AGE_KEYS.slice(AGE_KEYS.indexOf(age)).map(k => 'current_age = ' + k).join(' ') + ' }';
const slotTaken = brs => 'OR = { ' + brs.map(x => 'has_variable = ' + focusVar(x.id)).join(' ') + ' }';
const isNaval = br => /maritime|naval|fleet/.test(br.id);

// AI: pick one branch per empty slot of the current age, weighted (naval branches half weight).
function aiPickEffect() {
	const out = [];
	for (const a of ages) {
		for (const kind of ['eco', 'mil']) {
			const brs = a[kind];
			out.push('\t\t\tif = {');
			out.push('\t\t\t\tlimit = { current_age = ' + a.age + ' NOT = { ' + slotTaken(brs) + ' } }');
			out.push('\t\t\t\trandom_list = {');
			for (const br of brs) out.push('\t\t\t\t\t' + (isNaval(br) ? 50 : 100) + ' = { set_variable = ' + focusVar(br.id) + ' }');
			out.push('\t\t\t\t}');
			out.push('\t\t\t}');
		}
	}
	return out.join('\n');
}

function eventsFile() {
	return [
		'namespace = ages_of_eu',
		'namespace = abm_focus_picks',
		'',
		'# Ars Belli: same-name replacement of vanilla in_game/events/ages.txt (listed in replaced_files.txt).',
		'# GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js - edit focus_data.js and re-run.',
		'#',
		'# Vanilla ages_of_eu.1 (fired by the hardcoded on_new_age) offered one adm/dip/mil focus via',
		'# set_age_preference. That engine slot allows a single pick, so it is dropped entirely.',
		'# Every age from the Renaissance on has two focus slots (Economic, Military), 3 branches each.',
		'# Players pick in the Focus Picks panel (gui/shared/abm_focus_picks_panel.gui ->',
		'# scripted_guis/abm_focus_picks_gui.txt); AI countries pick here. A pick sets the country',
		'# variable abm_focus_<branch>, which the branch advances use as potential.',
		'#',
		'# abm_focus_picks.1 is a country_event, NOT age_event: the age event window has exactly three',
		'# cards bound to option keys adm/dip/mil and cannot show anything else.',
		'',
		'ages_of_eu.1 = {',
		'\ttype = country_event',
		'\thidden = yes',
		'',
		'\t# Age of Traditions has no focus picks.',
		'\ttrigger = {',
		'\t\tNOT = { current_age = age_1_traditions }',
		'\t}',
		'',
		'\timmediate = {',
		'\t\tif = {',
		'\t\t\tlimit = { is_ai = yes }',
		aiPickEffect(),
		'\t\t}',
		'\t\telse = {',
		'\t\t\ttrigger_event_non_silently = { id = abm_focus_picks.1 }',
		'\t\t}',
		'\t}',
		'}',
		'',
		'# Player notice: the new age\'s focuses are picked in the Focus Picks panel.',
		'abm_focus_picks.1 = {',
		'\ttype = country_event',
		'',
		'\ttitle = ages_of_eu.1.title',
		'\tdesc = abm_focus_picks.1.desc',
		'\toutcome = neutral',
		'',
		'\tillustration_tags = {',
		'\t\t10 = ages',
		'\t}',
		'',
		'\toption = {',
		'\t\tname = abm_focus_picks.1.a',
		'\t}',
		'}',
		'',
	].join('\n');
}

// Scripted GUIs behind the panel's Pick / Change buttons. Root = the player's country.
//   abm_focus_pick_<b>   shown while the slot (age + Economic/Military) is empty; valid once the age is reached
//   abm_focus_switch_<b> shown while a sibling branch holds the slot; costs 1 of MAX_CHANGES focus changes
//   abm_focus_pending    shown while the current age still has an empty slot (drives the "(!)" button)
function sguiFile() {
	const out = [];
	out.push('# Ars Belli focus picks: scripted GUIs for the Focus Picks panel. GENERATED by');
	out.push('# .tools/scripts/focus_picks/generate_focus_picks.js - edit focus_data.js and re-run.');
	out.push('# Change points: abm_focus_changes_used counts switches (missing = 0); at most ' + MAX_CHANGES + '.');
	for (const a of ages) {
		for (const kind of ['eco', 'mil']) {
			const brs = a[kind];
			for (const br of brs) {
				const others = brs.filter(x => x !== br);
				out.push('');
				out.push('abm_focus_pick_' + br.id + ' = {');
				out.push('\tscope = country');
				out.push('\tis_shown = { NOT = { ' + slotTaken(brs) + ' } }');
				out.push('\tis_valid = {');
				out.push('\t\tcustom_tooltip = {');
				out.push('\t\t\ttext = abm_focus_panel.' + a.age + '.reached_tt');
				out.push('\t\t\t' + ageReached(a.age));
				out.push('\t\t}');
				out.push('\t}');
				out.push('\teffect = { set_variable = ' + focusVar(br.id) + ' }');
				out.push('}');
				out.push('');
				out.push('abm_focus_switch_' + br.id + ' = {');
				out.push('\tscope = country');
				out.push('\tis_shown = {');
				out.push('\t\tNOT = { has_variable = ' + focusVar(br.id) + ' }');
				out.push('\t\t' + slotTaken(others));
				out.push('\t}');
				out.push('\tis_valid = {');
				out.push('\t\tcustom_tooltip = {');
				out.push('\t\t\ttext = ABM_FOCUS_CHANGES_NONE_TT');
				out.push('\t\t\tOR = {');
				out.push('\t\t\t\tNOT = { has_variable = abm_focus_changes_used }');
				out.push('\t\t\t\tvar:abm_focus_changes_used < ' + MAX_CHANGES);
				out.push('\t\t\t}');
				out.push('\t\t}');
				out.push('\t}');
				out.push('\teffect = {');
				for (const o of others) out.push('\t\tif = { limit = { has_variable = ' + focusVar(o.id) + ' } remove_variable = ' + focusVar(o.id) + ' }');
				out.push('\t\tset_variable = ' + focusVar(br.id));
				out.push('\t\tif = {');
				out.push('\t\t\tlimit = { has_variable = abm_focus_changes_used }');
				out.push('\t\t\tchange_variable = { name = abm_focus_changes_used add = 1 }');
				out.push('\t\t}');
				out.push('\t\telse = { set_variable = { name = abm_focus_changes_used value = 1 } }');
				out.push('\t}');
				out.push('}');
			}
		}
	}
	out.push('');
	out.push('abm_focus_pending = {');
	out.push('\tscope = country');
	out.push('\tis_shown = {');
	out.push('\t\tOR = {');
	for (const a of ages) {
		out.push('\t\t\tAND = {');
		out.push('\t\t\t\tcurrent_age = ' + a.age);
		out.push('\t\t\t\tOR = {');
		out.push('\t\t\t\t\tNOT = { ' + slotTaken(a.eco) + ' }');
		out.push('\t\t\t\t\tNOT = { ' + slotTaken(a.mil) + ' }');
		out.push('\t\t\t\t}');
		out.push('\t\t\t}');
	}
	out.push('\t\t}');
	out.push('\t}');
	out.push('}');
	return out.join('\n') + '\n';
}

// Focus changes left, as text (missing variable = none used).
function customLocFile() {
	const out = [
		'# Ars Belli focus picks: remaining focus changes. GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js',
		'abm_focus_changes_left = {',
		'\ttype = country',
	];
	for (let used = 0; used < MAX_CHANGES; used++) {
		out.push('\ttext = {');
		out.push('\t\tlocalization_key = ABM_FOCUS_CHANGES_LEFT_' + (MAX_CHANGES - used));
		out.push(used === 0
			? '\t\ttrigger = { NOT = { has_variable = abm_focus_changes_used } }'
			: '\t\ttrigger = { has_variable = abm_focus_changes_used var:abm_focus_changes_used = ' + used + ' }');
		out.push('\t}');
	}
	out.push('\ttext = {');
	out.push('\t\tlocalization_key = ABM_FOCUS_CHANGES_LEFT_0');
	out.push('\t}');
	out.push('}');
	return out.join('\n') + '\n';
}

function locFile() {
	const L = ['l_english:'];
	const q = s => s.replace(/"/g, '\\"');
	L.push(' # GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js - edit focus_data.js and re-run.');
	L.push('');
	L.push(' # Age event (player notice; AI countries pick automatically)');
	L.push(' abm_focus_picks.1.desc: "This is the dawning of the [GetCurrentAge.GetName]!\\n\\n[GetCurrentAge.GetDesc]\\n\\nThis [age|e] we choose #Y two#! focuses: one #Y Economic#! and one #Y Military#!. Each unlocks its own branch of six [advances|e]. Pick them in the #Y Focus Picks#! panel, from the button in the top right under the age."');
	L.push(' abm_focus_picks.1.a: "We will choose our focuses."');
	L.push('');
	L.push(' # Focus panel');
	L.push(' ABM_FOCUS_PANEL_TOGGLE: "Focus Picks"');
	L.push(' ABM_FOCUS_PANEL_TOGGLE_TOOLTIP: "Open the Focus Picks panel: every [age|e]\'s Economic and Military focus branches, the [advances|e] each one unlocks, and where we pick them."');
	L.push(' ABM_FOCUS_PANEL_TOGGLE_PENDING: "#Y Focus Picks (!)#!"');
	L.push(' ABM_FOCUS_PANEL_TOGGLE_PENDING_TOOLTIP: "#Y We have not picked all our focuses for this [age|e] yet.#!\\n\\nOpen the Focus Picks panel to choose one Economic and one Military focus."');
	L.push(' ABM_FOCUS_PANEL_TITLE: "Focus Picks"');
	L.push(' ABM_FOCUS_PANEL_CLOSE: "Close"');
	L.push(' ABM_FOCUS_PANEL_CLOSE_TOOLTIP: "Close the Focus Picks panel"');
	L.push(` ABM_FOCUS_PANEL_INTRO: "From the Renaissance on, each [age|e] we pick one #Y Economic#! and one #Y Military#! focus here, once that age has begun. Only the chosen branches appear in the [advances|e] tree, and picks from earlier ages stay researchable. Hover an advance to see its effects. A pick can be changed later, ${MAX_CHANGES} times per campaign; the advances of the replaced branch are lost."`);
	L.push(' ABM_FOCUS_PANEL_CHANGES: "Focus changes left: [Country.Custom(\'abm_focus_changes_left\')]"');
	for (let n = 0; n <= MAX_CHANGES; n++) L.push(` ABM_FOCUS_CHANGES_LEFT_${n}: "${n === 0 ? '#R 0#!' : '#G ' + n + '#!'}"`);
	L.push(` ABM_FOCUS_CHANGES_NONE_TT: "We have focus changes left (at most ${MAX_CHANGES} per campaign)"`);
	L.push(' ABM_FOCUS_PANEL_ECONOMIC: "#Y Economic Focus#!"');
	L.push(' ABM_FOCUS_PANEL_MILITARY: "#Y Military Focus#!"');
	L.push(' ABM_FOCUS_PANEL_PICKED: "#G Picked#!"');
	L.push(' ABM_FOCUS_PICK: "Pick"');
	L.push(' ABM_FOCUS_PICK_TT: "Pick this focus. Its six [advances|e] appear in the tree and can be researched."');
	L.push(' ABM_FOCUS_SWITCH: "Change to this"');
	L.push(` ABM_FOCUS_SWITCH_NONE_TT: "#R No focus changes left.#! A picked focus can be changed at most ${MAX_CHANGES} times per campaign."`);
	L.push(` ABM_FOCUS_SWITCH_TT: "Replace this [age|e]'s current pick in this row with this focus.\\n\\n#R Uses 1 of our ${MAX_CHANGES} focus changes.#! The replaced branch disappears from the tree, together with any of its [advances|e] already researched."`);
	for (const a of ages) {
		L.push(` abm_focus_panel.${a.age}: "Age of $${a.age}$"`);
		L.push(` abm_focus_panel.${a.age}.reached_tt: "The Age of $${a.age}$ has begun"`);
		L.push(` abm_focus_panel.${a.age}.not_reached_tt: "#R Not yet available.#! This focus can be picked once the Age of $${a.age}$ has begun."`);
	}
	for (const kind of ['eco', 'mil']) {
		for (const a of ages) {
			for (const br of a[kind]) {
				L.push('');
				L.push(` # ${a.age} - ${kind === 'eco' ? 'Economic' : 'Military'} - ${br.name}`);
				L.push(` abm_focus_picks.${br.id}: "${q(br.name)} Focus"`);
				const names = br.adv.map(x => `$${x[0]}$`).join(', ');
				// Single-line tooltips (no \n), like vanilla option .tt keys.
				L.push(` abm_focus_picks.${br.id}.tt: "${q(br.desc)}"`);
				L.push(` abm_focus_picks.${br.id}.unlocks_tt: "Unlocks the #Y ${q(br.name)}#! [advances|e]: ${names}"`);
				// Focus panel: one advance per line, as links whose tooltip shows the advance's effects.
				L.push(` abm_focus_panel.${br.id}.advances: "${br.adv.map(x => `• [ShowAdvanceName('${x[0]}')]`).join('\\n')}"`);
				for (const [key, , extra = {}] of br.adv) {
					if (!extra.name) continue;
					L.push(` ${key}: "${q(extra.name)}"`);
					L.push(` ${key}_desc: "${q(extra.desc)}"`);
				}
			}
		}
	}
	return L.join('\n') + '\n';
}

// Focus Picks panel: a GUI type placed in right_panel.gui next to the Tier List panel and toggled
// client-side via GetVariableSystem('abm_focus_panel_open') (per-player UI state, not a script var).
function guiFile() {
	// 3 cards + 2 x 6 spacing = 744 = panel inner width (780 - 2 x 8 margin - scrollbar).
	const CARD_W = 244;
	const TEXT_W = CARD_W - 10; // card margin 4 + frame
	const SGUI_SCOPE = 'GuiScope.SetRoot(GetPlayer.MakeScope).End'; // same form as the tier panel toggles
	// Each action is an enabled/disabled pair: a tooltip can't switch on validity, so the disabled
	// twin carries the reason (age not begun / no focus changes left).
	const btn = (sgui, text, okTip, noTip) => {
		const g = `GetScriptedGui('${sgui}')`;
		const shown = `${g}.IsShown(${SGUI_SCOPE})`;
		const valid = `${g}.IsValid(${SGUI_SCOPE})`;
		return `						button_regular = {
							text = "${text}"
							tooltip = "${okTip}"
							size = { ${TEXT_W} 26 }
							visible = "[And(${shown}, ${valid})]"
							onclick = "[${g}.Execute(${SGUI_SCOPE})]"
						}
						button_regular = {
							text = "${text}"
							tooltip = "${noTip}"
							size = { ${TEXT_W} 26 }
							enabled = no
							visible = "[And(${shown}, Not(${valid}))]"
						}`;
	};
	const card = (br, age) => `
					vbox = {
						minimumsize = { ${CARD_W} -1 }
						maximumsize = { ${CARD_W} -1 }
						layoutpolicy_vertical = expanding
						spacing = 2
						margin = { 4 4 }
						using = bg_cabinet_card_frame

						hbox = {
							layoutpolicy_horizontal = expanding
							spacing = 4
							text_single = {
								text = "abm_focus_picks.${br.id}"
								using = Font_Size_Medium
								align = left|nobaseline
								layoutpolicy_horizontal = expanding
							}
							text_single = {
								text = "ABM_FOCUS_PANEL_PICKED"
								using = Font_Size_Small
								visible = "[GetPlayer.MakeScope.GetVariable('${focusVar(br.id)}').IsSet]"
							}
						}
						text_multi = {
							text = "abm_focus_picks.${br.id}.tt"
							using = Font_Size_Small
							autoresize = yes
							align = left|nobaseline
							minimumsize = { ${TEXT_W} -1 }
							maximumsize = { ${TEXT_W} -1 }
						}
						text_multi = {
							text = "abm_focus_panel.${br.id}.advances"
							using = Font_Size_Small
							autoresize = yes
							align = left|nobaseline
							minimumsize = { ${TEXT_W} -1 }
							maximumsize = { ${TEXT_W} -1 }
						}
						expand = {}
${btn('abm_focus_pick_' + br.id, 'ABM_FOCUS_PICK', 'ABM_FOCUS_PICK_TT', 'abm_focus_panel.' + age + '.not_reached_tt')}
${btn('abm_focus_switch_' + br.id, 'ABM_FOCUS_SWITCH', 'ABM_FOCUS_SWITCH_TT', 'ABM_FOCUS_SWITCH_NONE_TT')}
					}`;
	const row = (label, brs, age) => `
				text_single = {
					text = "${label}"
					using = Font_Size_Small
				}
				hbox = {
					layoutpolicy_horizontal = expanding
					spacing = 6
${brs.map(br => card(br, age)).join('\n')}
				}`;
	const ageBlocks = ages.map(a => `
			# ${a.age}
			vbox = {
				layoutpolicy_horizontal = expanding
				spacing = 4
				text_single = {
					text = "abm_focus_panel.${a.age}"
					using = Font_Type_Headers
				}
${row('ABM_FOCUS_PANEL_ECONOMIC', a.eco, a.age)}
${row('ABM_FOCUS_PANEL_MILITARY', a.mil, a.age)}
			}`).join('\n');
	return `# Ars Belli Focus Picks panel. GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js
# Edit focus_data.js and re-run the generator instead of editing this file by hand.
# Placed in panels/right_panel/right_panel.gui (search "# Ars Belli focus picks panel"); opened by the
# "Focus Picks" button in the Tier List panel. Advance names use [ShowAdvanceName(...)], so hovering
# shows the game's own advance tooltip with its effects.
types AbmFocusPicksTypes
{
	# Always-visible opener under the age in the top right (not tied to the MP mechanics rule, unlike
	# the Tier List panel). Swaps to a highlighted "(!)" button while this age still has an empty slot.
	# Placed in right_panel.gui inside the rank block next to Tier List (a copy below the bar was
	# clipped and never showed), plus a standalone copy for games without the MP mechanics rule.
	type abm_focus_picks_button = flowcontainer {
		direction = horizontal

		button_regular = {
			text = "ABM_FOCUS_PANEL_TOGGLE"
			tooltip = "ABM_FOCUS_PANEL_TOGGLE_TOOLTIP"
			onclick = "[GetVariableSystem.Toggle('abm_focus_panel_open')]"
			size = { 100 22 }
			visible = "[Not(GetScriptedGui('abm_focus_pending').IsShown(${SGUI_SCOPE}))]"
		}
		button_regular = {
			text = "ABM_FOCUS_PANEL_TOGGLE_PENDING"
			tooltip = "ABM_FOCUS_PANEL_TOGGLE_PENDING_TOOLTIP"
			onclick = "[GetVariableSystem.Toggle('abm_focus_panel_open')]"
			size = { 120 22 }
			visible = "[GetScriptedGui('abm_focus_pending').IsShown(${SGUI_SCOPE})]"
		}
	}

	type abm_focus_picks_panel = widget {
		name = "abm_focus_picks_panel"
		layer = top
		parentanchor = top|right
		widgetanchor = top|right
		position = { -810 120 }
		size = { 780 760 }
		allow_outside = yes
		alwaystransparent = no
		visible = "[GetVariableSystem.Exists('abm_focus_panel_open')]"

		using = bg_paper_card
		using = bg_cabinet_card_frame

		vbox = {
			margin = { 8 8 }
			spacing = 6
			layoutpolicy_horizontal = expanding
			layoutpolicy_vertical = expanding

			hbox = {
				layoutpolicy_horizontal = expanding
				spacing = 4

				text_single = {
					text = "ABM_FOCUS_PANEL_TITLE"
					using = Font_Type_Headers
					align = left
					layoutpolicy_horizontal = expanding
				}

				button_regular = {
					text = "ABM_FOCUS_PANEL_CLOSE"
					tooltip = "ABM_FOCUS_PANEL_CLOSE_TOOLTIP"
					onclick = "[GetVariableSystem.Toggle('abm_focus_panel_open')]"
					size = { 80 26 }
				}
			}

			text_multi = {
				text = "ABM_FOCUS_PANEL_INTRO"
				using = Font_Size_Small
				autoresize = yes
				max_width = 760
			}

			text_single = {
				datacontext = "[GetPlayer]"
				text = "ABM_FOCUS_PANEL_CHANGES"
				using = Font_Size_Small
				align = left
			}

			scrollarea = {
				layoutpolicy_horizontal = expanding
				layoutpolicy_vertical = expanding
				scrollbarpolicy_horizontal = always_off
				scrollbar_vertical = {
					using = Scrollbar_Vertical
				}

				scrollwidget = {
					vbox = {
						layoutpolicy_horizontal = expanding
						spacing = 12
${ageBlocks}
					}
				}
			}
		}
	}
}
`;
}

write('in_game/gui/shared/abm_focus_picks_panel.gui', guiFile());
write('in_game/common/advances/abm_focus_picks_economic.txt', advancesFile('eco'));
write('in_game/common/advances/abm_focus_picks_military.txt', advancesFile('mil'));
write('in_game/events/ages.txt', eventsFile());
write('in_game/common/scripted_guis/abm_focus_picks_gui.txt', sguiFile());
write('in_game/common/customizable_localization/abm_focus_picks_custom_loc.txt', customLocFile());
write('main_menu/localization/english/abm_focus_picks_l_english.yml', locFile());
