// Generates the Ars Belli focus-pick system from focus_data.js:
//   in_game/common/advances/abm_focus_picks_economic.txt
//   in_game/common/advances/abm_focus_picks_military.txt
//   in_game/events/ages.txt                               (same-name replacement of vanilla)
//   main_menu/localization/english/abm_focus_picks_l_english.yml
//
// Usage (from repo root):  node .tools/scripts/focus_picks/generate_focus_picks.js
// Set EU5_GAME to override the vanilla game path used for icon lookup / REPLACE detection.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../..');
const GAME = process.env.EU5_GAME || 'E:/Steam/steamapps/common/Europa Universalis V/game';
const ADV_DIR = GAME + '/in_game/common/advances';
const { ages } = require('./focus_data.js');

const BOM = '\uFEFF';
const EOL = '\r\n';
const write = (rel, text, bom = true) => {
	fs.writeFileSync(path.join(ROOT, rel), (bom ? BOM : '') + text.replace(/\r?\n/g, EOL), 'utf8');
	console.log('wrote', rel);
};

// Vanilla advance blocks: key -> { file, icon }
const vanilla = {};
for (const f of fs.readdirSync(ADV_DIR).filter(f => f.endsWith('.txt'))) {
	const t = fs.readFileSync(path.join(ADV_DIR, f), 'utf8').replace(/^\uFEFF/, '');
	for (const m of t.matchAll(/^([A-Za-z_0-9]+)\s*=\s*\{([\s\S]*?)^\}/gm)) {
		const icon = (m[2].match(/^\s*icon\s*=\s*(\S+)/m) || [])[1];
		vanilla[m[1]] = { file: f, icon };
	}
}
const CHOICE_FILES = ['4_choices_adm.txt', '4_choices_dip.txt', '4_choices_mil.txt'];

const focusVar = id => `abm_focus_${id}`;
const indent = (s, n) => s.split('\n').map(l => (l ? '\t'.repeat(n) + l : l)).join('\n');

// Tree shape per branch: 0 is the root, 1->2 hang off 0, 3->4->5 hang off 0.
const PARENT = [null, 0, 1, 0, 3, 4];

function advanceBlock(ageKey, branch, idx) {
	const [key, mods, extra = {}] = branch.adv[idx];
	const v = vanilla[key];
	if (!v && !key.startsWith('abm_')) throw new Error(`vanilla advance not found: ${key}`);
	if (v && key.startsWith('abm_')) throw new Error(`abm_ key collides with vanilla: ${key}`);
	// Keys that live outside the emptied 4_choices files must be REPLACE:d, not redefined.
	const replace = v && !CHOICE_FILES.includes(v.file);
	const icon = extra.icon || (v && v.icon); // no icon line -> engine default, as in vanilla
	const lines = [];
	lines.push(`${replace ? 'REPLACE:' : ''}${key} = {`);
	lines.push(`\tage = ${ageKey}`);
	if (icon) lines.push(`\ticon = ${icon}`);
	// Branch roots must be explicit roots (depth = 0, like vanilla age roots): an advance with neither
	// requires nor depth gets auto-attached under another node by the engine (Mercenary landed under Court).
	if (PARENT[idx] === null) lines.push('\tdepth = 0');
	else lines.push(`\trequires = ${branch.adv[PARENT[idx]][0]}`);
	lines.push('');
	// potential (not allow): branches not picked stay hidden, like vanilla `for = X` focus advances.
	// potential IS re-checked in game, so a branch appears once its pick sets the variable. Hidden
	// branches also stop unparented vanilla/country advances being auto-attached under them.
	lines.push(`\tpotential = { has_variable = ${focusVar(branch.id)} }`);
	if (mods) { lines.push(''); lines.push(indent(mods, 1)); }
	if (extra.raw) { lines.push(''); lines.push(indent(extra.raw, 1)); }
	lines.push('}');
	return lines.join('\n');
}

function advancesFile(kind) {
	const title = kind === 'eco' ? 'Economic' : 'Military';
	const out = [];
	out.push(`# Ars Belli focus picks - ${title} advances. GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js`);
	out.push('# Edit focus_data.js and re-run the generator instead of editing this file by hand.');
	out.push('#');
	out.push('# Each age offers 3 branches; the pick made in the age event (ages_of_eu.1 / abm_focus_picks.1)');
	out.push('# sets a country variable abm_focus_<branch>, which is the only gate on these advances.');
	out.push('# The engine adm/dip/mil age preference (`for = X`) is no longer used: vanilla 4_choices_*.txt are emptied.');
	for (const a of ages) {
		for (const br of a[kind]) {
			out.push('');
			out.push('############################');
			out.push(`# ${a.age} - ${br.name} (${focusVar(br.id)})`);
			out.push('############################');
			br.adv.forEach((_, i) => { out.push(''); out.push(advanceBlock(a.age, br, i)); });
		}
	}
	return out.join('\n') + '\n';
}

function eventOptions(kind, next) {
	const out = [];
	for (const a of ages) {
		for (const br of a[kind]) {
			const naval = /maritime|naval|fleet/.test(br.id);
			out.push('\toption = {');
			// Dotted option names like every vanilla option (undotted ones showed a raw key in the tooltip).
			out.push(`\t\tname = abm_focus_picks.${br.id}`);
			out.push(`\t\ttrigger = { current_age = ${a.age} }`);
			out.push(`\t\thidden_effect = { set_variable = ${focusVar(br.id)} }`);
			out.push(`\t\tcustom_tooltip = abm_focus_picks.${br.id}.tt`);
			out.push(`\t\tcustom_tooltip = abm_focus_picks.${br.id}.unlocks_tt`);
			if (next) out.push(`\t\ttrigger_event_non_silently = { id = ${next} }`);
			out.push('');
			out.push('\t\tai_will_select = {');
			out.push(`\t\t\tvalue = ${naval ? 50 : 100}`);
			out.push('\t\t}');
			out.push('\t}');
		}
	}
	return out.join('\n');
}

function eventsFile() {
	return `namespace = ages_of_eu
namespace = abm_focus_picks

# Ars Belli: same-name replacement of vanilla in_game/events/ages.txt (listed in replaced_files.txt).
# GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js - edit focus_data.js and re-run.
#
# Vanilla ages_of_eu.1 (fired by the hardcoded on_new_age) offered one adm/dip/mil focus via
# set_age_preference. That engine slot allows a single pick, so it is dropped entirely.
# Instead every age from the Renaissance on asks for two picks, each out of 3 branches:
#   ages_of_eu.1        - Economic pick (economy and diplomacy branches)
#   abm_focus_picks.1   - Military pick (two land branches + one naval branch)
# A pick sets the country variable abm_focus_<branch>; the advances of that branch gate on it
# (see in_game/common/advances/abm_focus_picks_*.txt). Variables are never cleared, so picks
# from earlier ages stay researchable.
#
# Both are country_event, NOT age_event: the age event window (eventwindow.gui AgeEventWindow)
# has exactly three cards bound via EventWindow.AccessOptionItemWithKey('adm'/'dip'/'mil') with
# hardcoded Administrative/Diplomatic/Military tooltips. Options without those keys all fall back
# to the first option (every card showed the same focus in game), so it can't list our branches.

ages_of_eu.1 = {
	type = country_event

	title = ages_of_eu.1.title
	desc = abm_focus_picks.economic.desc
	outcome = neutral

	illustration_tags = {
		10 = ages
	}

	# Age of Traditions has no focus picks.
	trigger = {
		NOT = { current_age = age_1_traditions }
	}

${eventOptions('eco', 'abm_focus_picks.1')}
}

abm_focus_picks.1 = {
	type = country_event

	title = abm_focus_picks.1.title
	desc = abm_focus_picks.1.desc
	outcome = neutral

	illustration_tags = {
		10 = ages
	}

	trigger = {
		NOT = { current_age = age_1_traditions }
	}

${eventOptions('mil', null)}
}
`;
}

function locFile() {
	const L = ['l_english:'];
	const q = s => s.replace(/"/g, '\\"');
	L.push(' # GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js - edit focus_data.js and re-run.');
	L.push('');
	L.push(' # Age events');
	L.push(' abm_focus_picks.economic.desc: "This is the dawning of the [GetCurrentAge.GetName]!\\n\\n[GetCurrentAge.GetDesc]\\n\\nEach [age|e] we choose #Y two#! focuses: first an #Y Economic#! focus, then a #Y Military#! focus. Each focus unlocks its own branch of six [advances|e]; earlier picks stay researchable."');
	L.push(' abm_focus_picks.1.title: "Military Focus"');
	L.push(' abm_focus_picks.1.desc: "With our economic course set for the [GetCurrentAge.GetNameWithNoTooltip], we must now decide how our armies and fleets will be shaped."');
	L.push('');
	L.push(' # Focus panel (opened from the Tier List panel)');
	L.push(' ABM_FOCUS_PANEL_TOGGLE: "Focus Picks"');
	L.push(' ABM_FOCUS_PANEL_TOGGLE_TOOLTIP: "Show every [age|e]\'s Economic and Military focus branches and the [advances|e] each one unlocks."');
	L.push(' ABM_FOCUS_PANEL_TITLE: "Focus Picks"');
	L.push(' ABM_FOCUS_PANEL_CLOSE: "Close"');
	L.push(' ABM_FOCUS_PANEL_CLOSE_TOOLTIP: "Close the Focus Picks panel"');
	L.push(' ABM_FOCUS_PANEL_INTRO: "At the start of each [age|e] from the Renaissance on, we pick one #Y Economic#! and one #Y Military#! focus. Only the chosen branches appear in the [advances|e] tree, and earlier picks stay researchable. Hover an advance to see its effects."');
	L.push(' ABM_FOCUS_PANEL_ECONOMIC: "#Y Economic Focus#!"');
	L.push(' ABM_FOCUS_PANEL_MILITARY: "#Y Military Focus#!"');
	L.push(' ABM_FOCUS_PANEL_PICKED: "#G Picked#!"');
	for (const a of ages) L.push(` abm_focus_panel.${a.age}: "Age of $${a.age}$"`);
	for (const kind of ['eco', 'mil']) {
		for (const a of ages) {
			for (const br of a[kind]) {
				L.push('');
				L.push(` # ${a.age} - ${kind === 'eco' ? 'Economic' : 'Military'} - ${br.name}`);
				L.push(` abm_focus_picks.${br.id}: "${q(br.name)} Focus"`);
				const names = br.adv.map(x => `$${x[0]}$`).join(', ');
				// Single-line tooltips (no \n), like vanilla option .tt keys.
				L.push(` abm_focus_picks.${br.id}.tt: "${q(br.desc)}"`);
				L.push(` abm_focus_picks.${br.id}.unlocks_tt: "Unlocks the #Y ${q(br.name)}#! [advances|e]: ${names}"`);
				// Focus panel: one advance per line, as links whose tooltip shows the advance's effects.
				L.push(` abm_focus_panel.${br.id}.advances: "${br.adv.map(x => `• [ShowAdvanceName('${x[0]}')]`).join('\\n')}"`);
				for (const [key, , extra = {}] of br.adv) {
					if (!extra.name) continue;
					L.push(` ${key}: "${q(extra.name)}"`);
					L.push(` ${key}_desc: "${q(extra.desc)}"`);
				}
			}
		}
	}
	return L.join('\n') + '\n';
}

// Focus Picks panel: a GUI type placed in right_panel.gui next to the Tier List panel and toggled
// client-side via GetVariableSystem('abm_focus_panel_open') (per-player UI state, not a script var).
function guiFile() {
	const CARD_W = 230;
	const card = br => `
					vbox = {
						layoutpolicy_horizontal = expanding
						layoutpolicy_vertical = expanding
						spacing = 2
						margin = { 4 4 }
						using = bg_cabinet_card_frame

						hbox = {
							layoutpolicy_horizontal = expanding
							spacing = 4
							text_single = {
								text = "abm_focus_picks.${br.id}"
								using = Font_Size_Medium
								align = left|nobaseline
								layoutpolicy_horizontal = expanding
							}
							text_single = {
								text = "ABM_FOCUS_PANEL_PICKED"
								using = Font_Size_Small
								visible = "[GetPlayer.MakeScope.GetVariable('${focusVar(br.id)}').IsSet]"
							}
						}
						text_multi = {
							text = "abm_focus_picks.${br.id}.tt"
							using = Font_Size_Small
							autoresize = yes
							max_width = ${CARD_W}
						}
						text_multi = {
							text = "abm_focus_panel.${br.id}.advances"
							using = Font_Size_Small
							autoresize = yes
							max_width = ${CARD_W}
						}
						expand = {}
					}`;
	const row = (label, brs) => `
				text_single = {
					text = "${label}"
					using = Font_Size_Small
				}
				hbox = {
					layoutpolicy_horizontal = expanding
					spacing = 6
${brs.map(card).join('\n')}
				}`;
	const ageBlocks = ages.map(a => `
			# ${a.age}
			vbox = {
				layoutpolicy_horizontal = expanding
				spacing = 4
				text_single = {
					text = "abm_focus_panel.${a.age}"
					using = Font_Type_Headers
				}
${row('ABM_FOCUS_PANEL_ECONOMIC', a.eco)}
${row('ABM_FOCUS_PANEL_MILITARY', a.mil)}
			}`).join('\n');
	return `# Ars Belli Focus Picks panel. GENERATED by .tools/scripts/focus_picks/generate_focus_picks.js
# Edit focus_data.js and re-run the generator instead of editing this file by hand.
# Placed in panels/right_panel/right_panel.gui (search "# Ars Belli focus picks panel"); opened by the
# "Focus Picks" button in the Tier List panel. Advance names use [ShowAdvanceName(...)], so hovering
# shows the game's own advance tooltip with its effects.
types AbmFocusPicksTypes
{
	type abm_focus_picks_panel = widget {
		name = "abm_focus_picks_panel"
		layer = top
		parentanchor = top|right
		widgetanchor = top|right
		position = { -810 120 }
		size = { 780 760 }
		allow_outside = yes
		alwaystransparent = no
		visible = "[GetVariableSystem.Exists('abm_focus_panel_open')]"

		using = bg_paper_card
		using = bg_cabinet_card_frame

		vbox = {
			margin = { 8 8 }
			spacing = 6
			layoutpolicy_horizontal = expanding
			layoutpolicy_vertical = expanding

			hbox = {
				layoutpolicy_horizontal = expanding
				spacing = 4

				text_single = {
					text = "ABM_FOCUS_PANEL_TITLE"
					using = Font_Type_Headers
					align = left
					layoutpolicy_horizontal = expanding
				}

				button_regular = {
					text = "ABM_FOCUS_PANEL_CLOSE"
					tooltip = "ABM_FOCUS_PANEL_CLOSE_TOOLTIP"
					onclick = "[GetVariableSystem.Toggle('abm_focus_panel_open')]"
					size = { 80 26 }
				}
			}

			text_multi = {
				text = "ABM_FOCUS_PANEL_INTRO"
				using = Font_Size_Small
				autoresize = yes
				max_width = 760
			}

			scrollarea = {
				layoutpolicy_horizontal = expanding
				layoutpolicy_vertical = expanding
				scrollbarpolicy_horizontal = always_off
				scrollbar_vertical = {
					using = Scrollbar_Vertical
				}

				scrollwidget = {
					vbox = {
						layoutpolicy_horizontal = expanding
						spacing = 12
${ageBlocks}
					}
				}
			}
		}
	}
}
`;
}

write('in_game/gui/shared/abm_focus_picks_panel.gui', guiFile());
write('in_game/common/advances/abm_focus_picks_economic.txt', advancesFile('eco'));
write('in_game/common/advances/abm_focus_picks_military.txt', advancesFile('mil'));
write('in_game/events/ages.txt', eventsFile());
write('main_menu/localization/english/abm_focus_picks_l_english.yml', locFile());
