#!/usr/bin/env python3
"""Split Africa advances into regional files based on country definition files."""
import re, os, glob, csv, io, urllib.request
from pathlib import Path
from collections import defaultdict

# 1. Tag -> region from country definition files (authoritative)
tag_region = {}
files = sorted(glob.glob('/home/zp/Games/Modding/Ars-Belli-Mod/main_menu/setup/start/10_countries*.txt'))
for f in files:
    region = os.path.basename(f).replace('10_countries_', '').replace('_region.txt', '').replace('.txt', '')
    if region == '':
        region = 'other'
    with open(f, 'r', encoding='utf-8-sig') as fh:
        for line in fh:
            m = re.match(r'^\s*([A-Za-z0-9_]+)\s*=', line)
            if m and m.group(1) not in tag_region:
                tag_region[m.group(1)] = region

# 2. Sheet fallback for unknown tags
url = "https://docs.google.com/spreadsheets/d/1_43aH1mfGr6nag1VKuwexsLMvptkVPcj4OXo2QCfmnY/gviz/tq?tqx=out:csv&sheet=EU4%3EEU5"
resp = urllib.request.urlopen(url)
reader = csv.reader(io.StringIO(resp.read().decode('utf-8')))
rows = list(reader)

SECTIONS = ('East Africa', 'West Africa')
current_section = None
sheet_region = {}
for row in rows:
    if not row: continue
    first = row[0].strip() if row[0] else ''
    tag = row[1].strip() if len(row) > 1 else ''
    if first in SECTIONS and not tag:
        current_section = first
        continue
    if first == 'Europe': break
    if current_section and tag:
        sheet_region[tag] = current_section.lower().replace(' ', '_')

# 3. Final mapping: country file first, sheet fallback
final_region = {}
for t in tag_region:
    final_region[t] = tag_region[t]
for t in sheet_region:
    if t not in final_region:
        final_region[t] = sheet_region[t]

# 4. Parse advance blocks from the combined file
advance_dir = Path('/home/zp/Games/Modding/Ars-Belli-Mod/in_game/common/advances')
combined_file = advance_dir / 'abm_f5-t3_africa.txt'
all_blocks = []

with open(combined_file, 'r', encoding='utf-8-sig') as f:
    content = f.read()
lines = content.split('\n')
depth = 0
start = None
current_key = None
for i, line in enumerate(lines):
    if depth == 0:
        m = re.match(r'^([a-zA-Z0-9_]+)\s*=\s*\{', line)
        if m:
            current_key = m.group(1)
            start = i
            depth = 1
    else:
        depth += line.count('{') - line.count('}')
        if depth == 0:
            all_blocks.append((current_key, '\n'.join(lines[start:i+1])))

def extract_tags(block):
    return set(re.findall(r'has_or_had_tag\s*=\s*([A-Za-z0-9_]+)', block))

print(f"Parsed {len(all_blocks)} advance blocks")

# 5. Group by region
region_blocks = defaultdict(list)
region_seen = defaultdict(set)
unknown_tags = set()

for key, block in all_blocks:
    tags = extract_tags(block)
    assigned = False
    for tag in tags:
        region = final_region.get(tag)
        if region and key not in region_seen[region]:
            region_seen[region].add(key)
            region_blocks[region].append((key, block))
            assigned = True
            break
    if not assigned:
        unknown_tags.update(tags)

# 6. Write regional files + delete combined
header = "# Generated by .tools/generate_africa_advances.py\n# Source: EU4>EU5 Google Sheet + installed EU4 ideas and localization.\n"

for region in sorted(region_blocks):
    blks = region_blocks[region]
    filename = f"abm_f5-t3_{region}.txt"
    path = advance_dir / filename
    tags_in_file = set()
    with open(path, 'w', encoding='utf-8-sig', newline='\r\n') as f:
        f.write(header)
        f.write(f"\n# {region.upper().replace('_', ' ')}\n")
        for key, block in blks:
            f.write('\n')
            f.write(block)
            f.write('\n')
            tags_in_file.update(extract_tags(block))
    source = "country_file" if all(t in tag_region for t in tags_in_file) else "mixed"
    print(f"  {filename}: {len(blks)} advances, {len(tags_in_file)} tags [{source}]")

total = sum(len(b) for b in region_blocks.values())
print(f"\nTotal: {total} advances across {len(region_blocks)} regional files")

combined_file.unlink()
print(f"Deleted: {combined_file.name}")

if unknown_tags:
    print(f"\nWARNING: {len(unknown_tags)} tags not assigned to any region: {sorted(unknown_tags)}")

# 7. Show tag summary
print("\n=== TAG -> REGION ===")
by_region = defaultdict(list)
for t, r in sorted(final_region.items()):
    by_region[r].append(t)
for r in sorted(by_region):
    print(f"  {r}: {by_region[r]}")
